"""Seed data for the storefront. Edit here or via the admin API to change product content."""

SITE_SETTINGS = {
    "key": "site",
    "brand_name": "LedgerKit",
    "tagline": "Practical Digital Guides",
    "support_email": "ledgerkitsupport@gmail.com",
    "support_phone": "",
    "business_address": "",
    "support_hours": "",
    "response_time": "",
}

CATEGORIES = [
    {"slug": "marketing", "name": "Marketing"},
    {"slug": "meta-ads", "name": "Meta Ads"},
    {"slug": "business", "name": "Business"},
    {"slug": "digital-products", "name": "Digital Products"},
    {"slug": "ai", "name": "AI"},
    {"slug": "productivity", "name": "Productivity"},
    {"slug": "templates", "name": "Templates"},
    {"slug": "guides", "name": "Guides"},
]

CURRICULUM = [
    {"part": "Part 1", "title": "Digital Product Research", "topics": [
        "Don't Build First — Research First",
        "Meta Ad Library — Your First Research Tool",
        "What to Observe Inside Meta Ad Library",
        "Reference vs Copy — Research Ethically",
        "How to Find 5–6 Potential Niches",
        "Digital Product Opportunity Scorecard",
        "From Research to Testing — Choose What to Test",
    ]},
    {"part": "Part 2", "title": "Build a Product People Want", "topics": [
        "Find a Worthy Problem",
        "Validate the Product Idea",
        "Define the Before → After Transformation",
        "Create Strong Product Value",
        "Make the Product Easy to Consume",
        "Design for Shareability",
        "Build a Strong Product Title & Hook",
        "Make the Product Memorable",
        "Launch With Momentum",
        "Build Real Social Proof",
        "Turn an Idea Into a Digital Product",
        "Product Creation Checklist — Problem → Value → Product",
    ]},
    {"part": "Part 3", "title": "AI-Assisted Product Creation", "topics": [
        "AI Is Your Assistant — Not Your Replacement",
        "AI Product Creation Workflow — Idea to Launch",
        "How to Write Better AI Prompts",
        "Use Visual References Without Copying",
        "Reference → Design Principles → Original Design",
        "Choosing the Right Product Format & Presentation",
    ]},
    {"part": "Part 4", "title": "Website & Sales Page", "topics": [
        "Why Your Sales Page Matters",
        "Landing Page Hero Section",
        "Problem → Solution Section",
        "What's Included + Product Preview",
        "Benefits + Real Proof",
        "Pricing + Bonus + FAQ + CTA",
        "Ad Promise → Landing Page Message Match",
        "Checkout, Mobile Experience & Trust",
    ]},
    {"part": "Part 5", "title": "Tracking", "topics": [
        "Meta Pixel — Tracking Basics",
        "Important Events — ViewContent, Lead, Checkout, Purchase",
        "Conversions API — Simple Explanation",
        "Pixel + CAPI + Event Deduplication",
        "Tracking Setup Checklist",
    ]},
    {"part": "Part 6", "title": "Creative Strategy", "topics": [
        "Show the Actual Product",
        "Creative Formats — Video, Static, Carousel, UGC, Screen Recording",
        "The First 3 Seconds — Why the Hook Matters",
        "Problem Hooks + Curiosity Hooks",
        "Demonstration + Mistake + Outcome + Objection Hooks",
        "Hook → Body → CTA",
        "One Body, Multiple Hooks",
        "Creative Concepts vs Creative Variations",
        "Creative Testing Matrix",
        "Placement-Native Creative",
        "Mobile-First Design + Safe Zones + Captions",
        "Ad Copy Structure",
        "Creative Testing Workflow",
    ]},
    {"part": "Part 7", "title": "Meta Ads Fundamentals", "topics": [
        "Campaign → Ad Set → Ad",
        "Meta Campaign Objectives Explained",
        "Why Sales Objective Makes Sense for Purchase Goals",
        "Meta Targeting Terminology — Interests, Not “Keywords”",
        "Audience Sources",
        "Broad vs Interest vs Lookalike",
        "Creative Can Also Act as Targeting",
        "Meta Automation in 2026",
        "Manual Control vs Automation",
        "ABO — Ad Set Budget",
        "Campaign Budget / Advantage Campaign Budget",
        "ABO vs CBO — Practical Framework, Not a Universal Rule",
        "Set Up Your First Test Campaign",
    ]},
    {"part": "Part 8", "title": "Practical Testing System", "topics": [
        "Testing Budget — Example, Not a Rule",
        "Audience / Targeting Hypotheses",
        "Creative Variations Per Ad Set",
        "What to Observe While Testing",
        "Meta Ads 101 Metrics Cheat Sheet — Part 1",
        "Meta Ads 101 Metrics Cheat Sheet — Part 2",
        "Metric Hierarchy — Attention → Click → Funnel → Purchase → Economics",
        "Campaign Diagnostic Flow",
        "Do Not Overreact to One Good or Bad Day",
        "Kill / Continue Decision Framework",
        "Stop Guessing — Test Hypotheses",
        "Change One Major Variable at a Time",
        "Campaign Testing Log",
        "How to Find Winners",
    ]},
    {"part": "Part 9", "title": "Winner Analysis & Scaling", "topics": [
        "Ad Set Winner vs Ad-Level Winner",
        "Vertical Scaling",
        "Horizontal Scaling",
        "Understanding the Learning Phase",
        "Fragmentation vs Consolidation",
        "Finding Your Scaling Ceiling",
        "Cost Cap — Advanced Bidding Strategy",
    ]},
    {"part": "Part 10", "title": "Retargeting & Creative Fatigue", "topics": [
        "Retargeting Funnel — Cold → Warm → Hot → Customer",
        "Custom Audiences for Retargeting",
        "Retargeting Creative Angles",
        "How to Spot Creative Fatigue",
        "Creative Refresh System",
    ]},
    {"part": "Part 11", "title": "Offer & Funnel Optimization", "topics": [
        "The Offer Equation",
        "Testing Different Offer Packages",
        "Where Are You Losing Buyers? — Funnel Diagnostics",
        "Landing Page Conversion & Checkout Completion",
        "Unit Economics — What One Order Really Earns",
        "Break-Even CPA",
        "AOV — Bundles, Order Bumps & Upsells",
        "Profitable Scale vs Highest ROAS",
        "Meta Reporting vs Real Money",
    ]},
    {"part": "Part 12", "title": "Business Measurement", "topics": [
        "Revenue Reconciliation — Meta vs Gateway vs Bank",
        "Attribution Basics",
        "Attributed Sales vs Incremental Sales",
        "Profitability vs Cash Flow",
        "Customer Value Ladder",
        "Backend Offers — Solve the Next Problem",
        "Meta Ad Rejection Prevention",
        "Landing Page Compliance",
    ]},
    {"part": "Part 13", "title": "Operating the Business", "topics": [
        "Campaign Naming System",
        "Weekly Ads Review System",
        "What I Got Wrong / What I Would Do Differently",
        "Beginner Roadmap",
        "Advanced Roadmap",
    ]},
    {"part": "Bonus", "title": "Bonus Toolkit", "topics": [
        "Bonus Toolkit Overview",
        "20 AI Prompts — Part 1",
        "20 AI Prompts — Part 2",
        "Hook Bank — 10 Problem Hooks",
        "Hook Bank — 10 Curiosity Hooks",
        "Hook Bank — 10 Demonstration Hooks",
        "Hook Bank — 10 Mistake Hooks",
        "Hook Bank — 10 Outcome Hooks",
        "Printable Creative Testing Matrix",
        "Printable Meta Metrics Cheat Sheet",
        "Printable Campaign Testing Log",
        "Pre-Launch Checklist",
        "Daily Ads Checklist",
        "Weekly Review Checklist",
        "Landing Page Checklist",
        "Product Validation Checklist",
        "Full Diagnostic Decision Tree",
        "Final Master Framework — Research to Expansion",
    ]},
    {"part": "Case Studies", "title": "Real Case Studies", "topics": [
        "Real Case Study — Campaign Setup Context",
        "Real Case Study — Ad Set Winners & Losers",
        "Real Case Study — Ad-Level Winner",
    ]},
    {"part": "Closing", "title": "Closing", "topics": [
        "Final Business Principles",
    ]},
]

SAMPLE_PAGES = [
    {"label": "Page 4", "title": "My First Research Tool — Meta Ad Library", "kind": "Chapter", "image": "/samples/page-ad-library.webp"},
    {"label": "Page 35", "title": "The 3-Second Hook — 6 Proven Hook Types", "kind": "Chapter", "image": "/samples/page-hooks.webp"},
    {"label": "Page 37", "title": "Build a Page-View Retargeting Campaign", "kind": "Framework", "image": "/samples/page-retargeting.webp"},
    {"label": "Page 45", "title": "Reading Ad Set Performance — Real Ads Manager Data", "kind": "Real Example", "image": "/samples/page-adset-performance.webp"},
    {"label": "Page 64", "title": "When an Ad Stops Working — Creative Fatigue Signals", "kind": "Chapter", "image": "/samples/page-creative-fatigue.webp"},
    {"label": "Page 114", "title": "Real Case Study — Ad-Level Winner", "kind": "Case Study", "image": "/samples/page-ad-winner.webp"},
]

# Starter testimonials — replace these with genuine customer reviews as they come in.
TESTIMONIALS = [
    {"product_slug": "meta-ads-decode", "customer_name": "Aarav M.", "review": "Finally a guide that connects product creation and ads into one system. The diagnostic flow alone stopped me from killing a good campaign too early.", "verified_purchase": False},
    {"product_slug": "meta-ads-decode", "customer_name": "Sneha R.", "review": "I understood more about CPA and unit economics in one evening than from months of random videos. The checklists stay open while I work.", "verified_purchase": False},
    {"product_slug": "meta-ads-decode", "customer_name": "Rohan K.", "review": "The case studies showing winners and losers made the concepts click. It reads like someone sharing their actual working notebook.", "verified_purchase": False},
]

PHYSICAL_GALLERY_SLOTS = []

META_ADS_DECODE_PRODUCT = {
    "slug": "meta-ads-decode",
    "title": "Digital Product Sales Engine",
    "short_title": "Sales Engine",
    "tagline": "The complete digital product sales system — research, create, launch and scale — with real Meta Ads campaigns inside.",
    "cover_image": "/samples/sales-engine-cover.webp",
    "combo_checkout_urls": {
        "ai-business-ideas-2026": "https://superprofile.bio/vp/6aabbbe69c594000137ba85a",
        "chatgpt-prompt-guide": "https://superprofile.bio/vp/6aabbae09c594000137b7a66"
    },
    "download_url": "",
    "description": (
        "A complete digital product guide covering the full journey — finding and validating product ideas, "
        "creating the product, building the sales page, setting up tracking, crafting creatives, and running "
        "Meta Ads with real campaign examples, testing, analysis and scaling. Built from practical workflows, "
        "real Ads Manager examples, frameworks, checklists and case studies collected over 3 years of hands-on experience."
    ),
    "category": "digital-products",
    "product_type": "Guide",
    "format": "Digital PDF",
    "delivery_method": "Instant digital access after successful payment",
    "cta_text": "Get Meta Ads Decode",
    "currency": "INR",
    "regular_price": 1699,
    "sale_price": 299,
    "pages_count": "135+ Core Pages + Case Studies",
    "featured": True,
    "is_new": True,
    "bestseller": False,
    "status": "published",
    "offer_end": None,
    "landing_path": "/meta-ads-decode",
    "experience_years": 3,
    "whats_included": [
        "Complete Meta Ads Decode Guide — 13 parts from research to business measurement",
        "Real case studies — campaign setup, ad-set winners & losers, ad-level winner",
        "Bonus toolkit — AI prompts, hook banks and printable resources",
        "Printable checklists — pre-launch, daily ads, weekly review, landing page, validation",
        "Printable frameworks — creative testing matrix, metrics cheat sheet, testing log",
        "Full diagnostic decision tree and master framework (research → expansion)",
    ],
    "key_benefits": [
        "Learn a complete system — not isolated tips",
        "Understand why decisions are made, not just what to do",
        "See concepts inside real campaign scenarios",
        "Diagnose campaigns with structured frameworks instead of guessing",
        "Understand real business economics — CPA, AOV, profitability, cash flow",
        "Reusable checklists and cheat sheets you can return to anytime",
    ],
    "bonuses": [
        "20 AI prompts for product creation",
        "Hook bank — 50 hooks across 5 categories",
        "Printable creative testing matrix",
        "Printable Meta metrics cheat sheet",
        "Printable campaign testing log",
        "Pre-launch, daily, weekly and landing-page checklists",
    ],
    "curriculum": CURRICULUM,
    "sample_pages": SAMPLE_PAGES,
    "physical_gallery_slots": PHYSICAL_GALLERY_SLOTS,
    "who_for": [
        {"title": "Students", "text": "Understand digital products, online business and Meta advertising through practical examples rather than only theory."},
        {"title": "Side-Income Explorers", "text": "Learn the system behind researching, creating, testing and marketing digital products before spending money on random ideas."},
        {"title": "Beginners in Digital Business", "text": "You have an idea but don't yet understand validation, websites, offers, creatives, advertising or tracking."},
        {"title": "Existing Product Sellers", "text": "You already sell ebooks, templates or courses and want a more structured testing and advertising system."},
        {"title": "Small Business Owners", "text": "You want to understand how Meta Ads, creatives, offers and landing pages work together."},
    ],
    "not_for": [
        "Not a “get rich quick” formula",
        "Not guaranteed campaign results",
        "Not a collection of random hacks",
        "Not a promise that one campaign structure works for everyone",
        "Not copied advertising creatives",
        "Not a substitute for testing in your own business",
    ],
    "faqs": [
        {"q": "Is this suitable for beginners?", "a": "Yes. Foundations are covered first — campaign structure, objectives, targeting and tracking — before the guide moves into testing systems, diagnostics and scaling."},
        {"q": "Does this guarantee profitable ads?", "a": "No. Advertising performance depends on your product, offer, market, creative, website, competition, pricing and many other factors. This guide is educational and results vary."},
        {"q": "Is this only about Meta Ads?", "a": "No. It covers the wider digital-product system — research, product development, website, tracking, creative strategy, advertising, funnel economics and business measurement."},
        {"q": "Is this a physical book?", "a": "No — this is a 100% digital product. You get instant online access after successful payment; nothing is shipped."},
        {"q": "How will I receive access?", "a": "Instantly. After successful payment confirmation you receive digital access through the configured delivery method (download page / email)."},
        {"q": "Does it contain practical examples?", "a": "Yes. The guide includes frameworks and campaign examples to explain decision-making, including case studies of campaign setup, ad-set winners & losers and an ad-level winner."},
        {"q": "Is Meta affiliated with this product?", "a": "No. This is an independent educational product and is not sponsored, endorsed or administered by Meta Platforms, Inc."},
    ],
    "editions": {
        "digital": {
            "label": "Digital Edition",
            "badge": "Instant Access",
            "price": 299,
            "cta": "Get Instant Access",
            "note": "Secure Checkout • Digital Product • Instant Access",
            "checkout_url": "https://superprofile.bio/vp/6aab089e0cce8b001386b6f9",
            "features": [
                "Complete Meta Ads Decode Guide — the full digital product system",
                "Digital PDF / ebook edition",
                "Read on phone, tablet or laptop",
                "Searchable digital format where supported",
                "Real Meta Ads campaign examples & case studies",
                "Bonus printable resources included",
            ],
        },
    },
}

AI_IDEAS_PRODUCT = {
    "slug": "ai-business-ideas-2026",
    "title": "AI Business Ideas Guide 2026",
    "short_title": "AI Ideas 2026",
    "cover_image": "/samples/ai-ideas-cover.webp",
    "tagline": "Automation-ready AI business ideas you can start lean — with tools, workflows and monetization paths for each.",
    "description": "A practical guide to AI-powered business ideas for 2026 that run on automation. Each idea includes the tools stack, the workflow, and how it makes money — so you can pick one and start building instead of scrolling for inspiration.",
    "category": "ai",
    "product_type": "Guide",
    "format": "Digital PDF",
    "delivery_method": "Instant digital access after successful payment",
    "cta_text": "Get Instant Access",
    "currency": "INR",
    "regular_price": None,
    "sale_price": 199,
    "featured": False,
    "is_new": True,
    "bestseller": False,
    "status": "published",
    "offer_end": None,
    "whats_included": [
        "50+ AI business ideas for 2026",
        "Automation-first workflow for each idea",
        "Recommended tools stack per idea",
        "Monetization paths explained simply",
        "Beginner friendly — no coding needed",
    ],
    "key_benefits": [],
    "bonuses": [],
    "curriculum": [],
    "sample_pages": [],
    "who_for": [],
    "not_for": [],
    "faqs": [],
    "editions": {
        "digital": {
            "label": "Digital Edition",
            "badge": "Instant Access",
            "price": 199,
            "cta": "Get Instant Access",
            "note": "Secure Checkout • Digital Product • Instant Access",
            "checkout_url": "",
            "features": [],
        },
    },
}

PROMPT_GUIDE_PRODUCT = {
    "slug": "chatgpt-prompt-guide",
    "title": "ChatGPT Prompt Guide",
    "short_title": "Prompt Guide",
    "cover_image": "/samples/prompt-guide-cover.webp",
    "tagline": "Ready-to-use prompts for product research, ebook creation, landing page copy, hooks and ads.",
    "description": "A copy-paste prompt library for digital product builders. Covers product research, ebook creation, landing page copy, ad hooks and ad copy — the exact prompts that turn ChatGPT into a useful assistant instead of a generic content machine.",
    "category": "ai",
    "product_type": "Prompt Library",
    "format": "Digital PDF",
    "delivery_method": "Instant digital access after successful payment",
    "cta_text": "Get Instant Access",
    "currency": "INR",
    "regular_price": None,
    "sale_price": 149,
    "featured": False,
    "is_new": True,
    "bestseller": False,
    "status": "published",
    "offer_end": None,
    "whats_included": [
        "Product research & validation prompts",
        "Ebook creation prompts",
        "Landing page copy prompts",
        "Ad hook & ad copy prompts",
        "Copy-paste ready format",
    ],
    "key_benefits": [],
    "bonuses": [],
    "curriculum": [],
    "sample_pages": [],
    "who_for": [],
    "not_for": [],
    "faqs": [],
    "editions": {
        "digital": {
            "label": "Digital Edition",
            "badge": "Instant Access",
            "price": 149,
            "cta": "Get Instant Access",
            "note": "Secure Checkout • Digital Product • Instant Access",
            "checkout_url": "",
            "features": [],
        },
    },
}

BUNDLE_PRODUCT = {
    "slug": "complete-business-bundle",
    "title": "Complete Business Bundle",
    "short_title": "Business Bundle",
    "cover_image": "/samples/bundle-covers.webp",
    "tagline": "Digital Product Sales Engine + AI Business Ideas 2026 + ChatGPT Prompt Guide — the full stack in one purchase.",
    "description": "Everything you need to research, build, market and scale a digital product business: the complete Sales Engine guide, 50+ automation-ready AI business ideas, and the copy-paste ChatGPT prompt library — together at a bundle price.",
    "category": "business",
    "product_type": "Bundle",
    "format": "Digital PDF",
    "delivery_method": "Instant digital access after successful payment",
    "cta_text": "Get the Bundle",
    "currency": "INR",
    "regular_price": 647,
    "sale_price": 499,
    "featured": False,
    "is_new": True,
    "bestseller": False,
    "status": "published",
    "offer_end": None,
    "whats_included": [
        "Digital Product Sales Engine (₹299 value)",
        "AI Business Ideas Guide 2026 (₹199 value)",
        "ChatGPT Prompt Guide (₹149 value)",
        "Instant digital access to all three",
    ],
    "key_benefits": [],
    "bonuses": [],
    "curriculum": [],
    "sample_pages": [],
    "who_for": [],
    "not_for": [],
    "faqs": [],
    "editions": {
        "digital": {
            "label": "Complete Bundle",
            "badge": "Best Value",
            "price": 499,
            "cta": "Get Complete Bundle",
            "note": "Secure Checkout • Digital Products • Instant Access",
            "checkout_url": "https://superprofile.bio/vp/6aabaf99aa63460013c9c19f",
            "features": [],
        },
    },
}
