// Editable legal & policy content. Replace [PLACEHOLDER] tokens with your actual business details.

export const LEGAL_PAGES = {
  "terms-and-conditions": {
    title: "Terms & Conditions",
    updated: "Last updated: [INSERT DATE]",
    intro: "These Terms & Conditions govern your purchase and use of digital and physical educational products from [BRAND NAME] (“we”, “us”, “our”). By accessing this website or purchasing a product, you agree to these terms.",
    sections: [
      { heading: "1. Acceptance of Terms", body: ["By using this website or purchasing any product, you confirm that you have read, understood and agree to be bound by these Terms & Conditions, along with our Privacy Policy, Refund & Cancellation Policy and Delivery policies."] },
      { heading: "2. Eligibility", body: ["You must be at least 18 years of age, or have the involvement of a parent or legal guardian, to make a purchase on this website."] },
      { heading: "3. Digital Product Purchase", body: ["Unless stated otherwise, our products are digital educational resources (guides, ebooks, templates and related materials). Access or download instructions are provided after successful payment confirmation through the configured delivery method."] },
      { heading: "4. Intellectual Property", body: ["All content, including text, frameworks, diagrams, checklists, screenshots and design, is the intellectual property of [BRAND NAME] and is protected by applicable copyright laws."] },
      { heading: "5. Personal-Use Licence", body: ["Unless explicitly stated otherwise, purchases grant you a non-exclusive, non-transferable licence for personal use only. You may not redistribute, resell, share, upload publicly, or republish the product or any part of it without written permission."] },
      { heading: "6. Payments & Pricing", body: ["Prices are listed in Indian Rupees (INR) unless stated otherwise and may change at any time. Payment is processed by our configured payment provider. We do not store your full payment instrument details on this website."] },
      { heading: "7. Product Access", body: ["You are responsible for providing an accurate email address and contact details. If you do not receive access after a successful payment, contact us using the details on our Contact page and we will resolve the issue."] },
      { heading: "8. Educational Nature of Content", body: ["Our products are educational resources. They explain systems, frameworks and workflows based on practical experience. They do not constitute professional business, financial, legal or tax advice."] },
      { heading: "9. Results Disclaimer", body: ["Advertising and business outcomes vary based on product, market, offer, creative, budget, competition and execution. We do not guarantee any specific results, revenue or profitability from applying the material."] },
      { heading: "10. Third-Party Platforms", body: ["Our content references third-party platforms such as Meta. Features, interfaces, terminology and policies of those platforms may change at any time. This is an independent product and is not sponsored, endorsed or administered by Meta Platforms, Inc."] },
      { heading: "11. Refunds", body: ["Refunds and cancellations are governed by our Refund & Cancellation Policy, available in the footer of this website. Please review it before purchasing."] },
      { heading: "12. Prohibited Use", body: ["You may not misuse this website, attempt unauthorised access, scrape content at scale, or use the products for any unlawful purpose."] },
      { heading: "13. Limitation of Liability", body: ["To the maximum extent permitted by law, [BRAND NAME] shall not be liable for indirect, incidental or consequential damages arising from the use of our products or website."] },
      { heading: "14. Changes to Products & Content", body: ["We may update, improve or discontinue products and content at any time. Material updates to purchased digital products may be provided at our discretion."] },
      { heading: "15. Governing Law", body: ["These terms are governed by the laws of India. Jurisdiction: [INSERT JURISDICTION / COURTS]."] },
      { heading: "16. Contact", body: ["For any questions about these terms, contact us at [SUPPORT EMAIL] or [PHONE NUMBER]. Business address: [PHYSICAL BUSINESS ADDRESS]."] },
    ],
  },
  "privacy-policy": {
    title: "Privacy Policy",
    updated: "Last updated: [INSERT DATE]",
    intro: "This Privacy Policy explains what information [BRAND NAME] collects, how it is used, and the choices you have.",
    sections: [
      { heading: "1. Information We Collect", body: ["Contact information you provide (name, email, phone) through forms or checkout.", "Transaction information related to your purchases (product, edition, amount, order ID).", "Website usage data such as pages visited, device and browser information."] },
      { heading: "2. Payment Information", body: ["Payments are processed directly by our configured payment provider (for example, SuperProfile or Razorpay). Your card, UPI or banking details are processed by the provider and are not stored on this website."] },
      { heading: "3. Cookies & Analytics", body: ["We may use cookies and analytics tools to understand how the website is used and to improve it. Where enabled, advertising technologies such as the Meta Pixel may be used to measure campaign performance."] },
      { heading: "4. How We Use Information", body: ["To deliver your products and provide access instructions.", "To respond to support queries.", "To process refunds or resolve payment issues.", "To improve our website, products and communication."] },
      { heading: "5. Data Sharing", body: ["We do not sell your personal information. Information may be shared with service providers strictly as needed — for example payment processors, email delivery services and courier partners for physical orders."] },
      { heading: "6. Data Retention", body: ["We retain order and contact records for as long as needed to provide support, meet legal obligations and maintain business records: [INSERT RETENTION PERIOD]."] },
      { heading: "7. Security", body: ["We take reasonable measures to protect your information. No method of transmission or storage is completely secure, and we encourage you to contact us immediately if you suspect any issue."] },
      { heading: "8. Your Rights", body: ["You may request access, correction or deletion of your personal information by contacting us at [SUPPORT EMAIL]."] },
      { heading: "9. Third-Party Services", body: ["Our website links to or integrates third-party services (payment providers, analytics, advertising platforms). Their own privacy policies apply to their processing of your data."] },
      { heading: "10. Changes to This Policy", body: ["We may update this policy from time to time. The latest version will always be available on this page."] },
      { heading: "11. Contact", body: ["Questions about privacy: [SUPPORT EMAIL] • [PHONE NUMBER]."] },
    ],
  },
  "refund-cancellation-policy": {
    title: "Refund & Cancellation Policy",
    updated: "Last updated: [INSERT DATE]",
    intro: "This policy explains how refunds and cancellations work for digital editions, physical books and bundles purchased from [BRAND NAME]. Please read it before purchasing.",
    sections: [
      { heading: "1. Digital Edition", body: ["Refund eligibility for downloadable digital products: [INSERT POLICY].", "Refund request period: [INSERT PERIOD].", "Because digital products are delivered instantly, please describe the issue in detail when requesting support so we can resolve it quickly."] },
      { heading: "2. Physical Book", body: ["Cancellation before dispatch: [INSERT CANCELLATION POLICY].", "Damaged or incorrect book received: contact us within [INSERT PERIOD] with your order ID and photos of the item, and we will arrange [REPLACEMENT / REFUND — INSERT PROCEDURE].", "Return eligibility & period: [INSERT RETURN POLICY].", "Delivery failure: [INSERT PROCEDURE]."] },
      { heading: "3. Digital + Physical Bundle", body: ["Because digital access is provided immediately while the physical copy ships separately, bundle refunds are handled as follows: [INSERT BUNDLE REFUND POLICY — e.g. how refunds work when digital access is already delivered but the book has not shipped]."] },
      { heading: "4. Duplicate or Failed Payments", body: ["If you were charged twice for the same order, or charged without receiving access, contact us with your payment/order ID. Verified duplicate payments are refunded to the original payment method. Failed payments where money was debited are typically reversed automatically by your bank or the payment provider within [INSERT TIMELINE]."] },
      { heading: "5. Refund Processing", body: ["Approved refunds are processed to the original payment method. Processing timeline: [INSERT TIMELINE]."] },
      { heading: "6. How to Request", body: ["Contact us at [SUPPORT EMAIL] or [PHONE NUMBER] with your name, order/payment ID and the reason for your request."] },
    ],
  },
  "shipping-delivery-policy": {
    title: "Shipping & Delivery Policy",
    updated: "Last updated: [INSERT DATE]",
    intro: "This policy applies to physical products such as the printed edition of Meta Ads Decode. Digital products are covered by our Digital Delivery Policy.",
    sections: [
      { heading: "1. Order Processing", body: ["Orders are processed within: [INSERT ACTUAL PROCESSING TIME]."] },
      { heading: "2. Dispatch Timeline", body: ["Estimated dispatch: [INSERT ACTUAL DISPATCH TIMELINE]."] },
      { heading: "3. Estimated Delivery", body: ["Estimated delivery after dispatch: [INSERT ACTUAL DELIVERY RANGE]."] },
      { heading: "4. Shipping Charges", body: ["Shipping charges: [FREE / FIXED / CALCULATED AT CHECKOUT — INSERT ACTUAL]."] },
      { heading: "5. Service Area", body: ["We currently ship to: [INDIA / SELECTED LOCATIONS — INSERT ACTUAL]."] },
      { heading: "6. Courier Partners", body: ["Courier partners used: [INSERT ACTUAL COURIER PARTNERS]."] },
      { heading: "7. Tracking", body: ["Where tracking is available, tracking details are shared via [EMAIL / SMS / WHATSAPP — INSERT ACTUAL] once your order is dispatched."] },
      { heading: "8. Incorrect Address", body: ["Please double-check your shipping address, PIN code and phone number at checkout. We are not responsible for delays or failed delivery caused by incorrect address details provided by the customer."] },
      { heading: "9. Delivery Delays", body: ["Courier and logistics delays can occasionally occur due to weather, strikes or regional restrictions. We will support you in tracking delayed shipments."] },
      { heading: "10. Lost or Damaged Shipment", body: ["If your shipment arrives damaged or is lost in transit, contact us within [INSERT PERIOD] with your order ID and photos where applicable. Resolution procedure: [INSERT REPLACEMENT / REFUND PROCEDURE]."] },
      { heading: "11. Contact", body: ["Shipping queries: [SUPPORT EMAIL] • [PHONE NUMBER]."] },
    ],
  },
  "digital-delivery-policy": {
    title: "Digital Delivery Policy",
    updated: "Last updated: [INSERT DATE]",
    intro: "This policy explains how digital products from [BRAND NAME] are delivered.",
    sections: [
      { heading: "1. Digital Products Only", body: ["Unless you order a physical edition, our products are digital. No physical shipment is made for digital-only purchases. Physical shipping is not applicable to digital-only products."] },
      { heading: "2. When Delivery Starts", body: ["Delivery begins after successful payment confirmation from our payment provider."] },
      { heading: "3. How Delivery Happens", body: ["Depending on the configured delivery method, access may be provided via a download page, account access, email, SuperProfile or another configured platform."] },
      { heading: "4. Accurate Contact Information", body: ["Please provide an accurate email address and phone number at checkout. Access instructions are sent to the details you provide."] },
      { heading: "5. If You Do Not Receive Access", body: ["Check your spam/promotions folder first. If you still cannot find your access, contact us with your order/payment ID and we will resolve it: [SUPPORT EMAIL] • [PHONE NUMBER]."] },
    ],
  },
  "disclaimer": {
    title: "Disclaimer",
    updated: "Last updated: [INSERT DATE]",
    intro: "Please read this disclaimer carefully before using our products.",
    sections: [
      { heading: "Educational Purposes Only", body: ["All products and content are provided for educational purposes only."] },
      { heading: "No Guaranteed Results", body: ["Advertising and business outcomes vary based on product, market, offer, creative, budget, competition and execution. We do not guarantee any specific result, revenue or profitability."] },
      { heading: "Examples", body: ["Campaign examples and case studies demonstrate concepts and decision-making. They should not be interpreted as guaranteed outcomes for your campaigns."] },
      { heading: "Platform Changes", body: ["Meta features, interfaces, terminology and policies can change at any time. Always refer to official Meta documentation for the latest platform behaviour."] },
      { heading: "Independent Product", body: ["This business is not affiliated with, endorsed by, sponsored by or administered by Meta Platforms, Inc."] },
      { heading: "Professional Advice", body: ["Business, financial, legal or tax information in our guides should not replace advice from qualified professionals where applicable."] },
    ],
  },
};

export const LEGAL_SLUGS = Object.keys(LEGAL_PAGES);
